'use strict';
const bi=(ru,en)=>ODILang.t(ru);
let live={},liveAt=0,liveError='',liveTimer=null,liveReading=false,ponHistory=[],fullDiagnostic={};
async function readApi(query,timeout=30000){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);
 try{const res=await fetch('api.cgi?'+query,{credentials:'same-origin',cache:'no-store',signal:controller.signal}),body=await res.text();
  if(res.status===401||res.status===403||body.trimStart().startsWith('<')){showAuth();throw new Error(bi('Требуется вход администратора.','Administrator sign-in required.'));}
  const out={};for(const line of body.trim().split('\n')){const p=line.indexOf('=');if(p>0)out[line.slice(0,p)]=decode(line.slice(p+1));}
  if(!res.ok||out.ok!=='1')throw new Error(out.error||bi('Данные временно недоступны.','Data temporarily unavailable.'));return out;
 }finally{clearTimeout(timer);}
}
function downloadJSON(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function ponStage(raw){if(!raw||/READ_ERROR|not found|unsupported|failed|error/i.test(raw))return null;let m=raw.match(/\bO([1-7])\b/i)||raw.match(/(?:ONU\s*State|ONUState|onu-state|state)\s*[:=]\s*([1-7])\b/i);return m?'O'+m[1]:null;}
function numericMetric(raw){if(!raw||/READ_ERROR|not found|failed|error|unsupported/i.test(raw))return '—';const lines=raw.split(/[\r\n]/).map(s=>s.trim()).filter(s=>s&&!/^(?:RTK[\w.]*>|command:|pon\s+get\s+transceiver\b)/i.test(s));return (lines.at(-1)||'—').replace(/^(?:Rx Power|Tx Power|Temperature|Voltage|Bias Current)\s*:\s*/i,'');}
function stageHint(stage){const hints={O1:bi('Инициализация: проверьте наличие сигнала и режим PON.','Initialisation: check optical signal and PON mode.'),O2:bi('Ожидание параметров от OLT.','Waiting for OLT parameters.'),O3:bi('Обмен серийным номером: сравните GPON SN с рабочим профилем.','Serial-number exchange: compare GPON SN with the working profile.'),O4:bi('Ranging: проверьте регистрацию и совместимость с OLT.','Ranging: check registration and OLT compatibility.'),O5:bi('Регистрация активна. Интернет дополнительно зависит от OMCI, GEM и VLAN.','Registration active. Internet also depends on OMCI, GEM and VLAN.'),O6:bi('Потеря синхронизации: проверьте оптику и историю переходов.','Loss of synchronisation: check optics and transition history.'),O7:bi('Передатчик отключён: проверьте состояние на стороне OLT.','Transmitter disabled: check OLT status.')};return hints[stage]||bi('Состояние не распознано. Посмотрите исходный вывод ниже.','State not recognised. Check the raw output below.');}
function liveCard(){return card(bi('Регистрация и оптика','Registration and optics'),bi('Автообновление без перезаписи открытых форм.','Automatic refresh preserves open forms.'),'<div id="live-data" aria-live="polite"></div><p id="live-stamp" class="muted"></p><div class="utility-links"><a href="#diagnostics">'+bi('Подробная диагностика','Detailed diagnostics')+'</a><a href="/status_pon.asp" target="_blank" rel="noopener">'+bi('Штатное состояние PON ↗','Factory PON status ↗')+'</a></div>');}
function paintLive(){paintShellTelemetry();const root=document.getElementById('live-data');if(!root)return;const stage=ponStage(live.pon_state),fresh=liveAt&&Date.now()-liveAt<25000&&!liveError;
 root.innerHTML='<div class="telemetry-grid">'+[
 [bi('Состояние PON','PON state'),stage||'—'],['RX',numericMetric(live['optic_rx-power'])],['TX',numericMetric(live['optic_tx-power'])],
 [bi('Температура','Temperature'),numericMetric(live.optic_temperature)],[bi('Напряжение','Voltage'),numericMetric(live.optic_voltage)],[bi('Ток лазера','Laser bias'),numericMetric(live['optic_bias-current'])]
 ].map(([k,v])=>'<div><small>'+esc(k)+'</small><strong>'+esc(v)+'</strong></div>').join('')+'</div><p>'+esc(stageHint(stage))+'</p><dl class="details">'+detail(bi('Время работы, секунд','Uptime, seconds'),live.sampled_uptime||state.uptime?.split(' ')[0])+detail(bi('Режим порта · фактический','Port mode · actual'),live.link_actual||state.link_actual)+'</dl>';
 document.getElementById('live-stamp').textContent=(fresh?bi('Обновлено: ','Updated: '):bi('Данные устарели или недоступны: ','Data stale or unavailable: '))+(liveAt?new Date(liveAt).toLocaleTimeString():'—')+(liveError?' · '+liveError:'');
 paintHistory();
}
function paintHistory(){const root=document.getElementById('pon-history');if(root)root.innerHTML=ponHistory.length?'<div class="table-scroll"><table class="data-table"><thead><tr><th>'+bi('Время браузера','Browser time')+'</th><th>'+bi('Переход','Transition')+'</th></tr></thead><tbody>'+ponHistory.map(x=>'<tr><td>'+esc(x.time)+'</td><td>'+esc(x.stage)+'</td></tr>').join('')+'</tbody></table></div>':'<p class="muted">'+bi('История начнётся после первого чтения. Хранится только в этой вкладке.','History starts after the first read and is kept only in this browser tab.')+'</p>';}
function liveTabEnabled(){return interfaceLayout==='diagnostic'||['overview','diagnostics','mods','link'].includes(tab);}
async function pollLive(){clearTimeout(liveTimer);if(!liveTabEnabled()||document.hidden||preview)return;if(liveReading||busy){paintShellTelemetry();liveTimer=setTimeout(pollLive,3000);return;}liveReading=true;
 try{const next=await readApi('telemetry'),stage=ponStage(next.pon_state);live=next;liveAt=Date.now()-Number(next.collection_seconds||0)*1000;liveError='';if(stage&&stage!==ponHistory.at(-1)?.stage){ponHistory.push({time:new Date().toLocaleTimeString(),stage,uptime:next.sampled_uptime});if(ponHistory.length>120)ponHistory.shift();}paintLive();paintModRuntime();}
 catch(e){liveError=e.message;paintLive();}finally{liveReading=false;if(liveTabEnabled())liveTimer=setTimeout(pollLive,5000);}
}
async function pauseLive(){clearTimeout(liveTimer);while(liveReading)await new Promise(resolve=>setTimeout(resolve,100));clearTimeout(liveTimer);}
function restartLive(){clearTimeout(liveTimer);paintLive();paintModRuntime();if(!preview)liveTimer=setTimeout(pollLive,100);}
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(liveTimer);else restartLive();});
function mibRecords(raw){const rows=[];let current=null;for(const line of String(raw||'').split('\n')){const m=line.match(/^\s*Entity\s*ID\s*:\s*(0x[0-9a-f]+|\d+)/i);if(m){current={id:m[1],lines:[]};rows.push(current);}else if(current&&line.trim())current.lines.push(line.trim());}return rows;}
function vlanRows(data){const rows=[];for(const cls of [84,171,78])for(const record of mibRecords(data['me_'+cls]))for(const line of record.lines){let match;const re=/\bVID\s*[:=]?\s*(0x[0-9a-f]+|\d+)/ig;while((match=re.exec(line))){const n=Number(match[1]);rows.push({class:cls,entity:record.id,vid:n,rule:line});}}return rows;}
function diagnosticTables(data){const rows=vlanRows(data),vlan=rows.length?'<div class="table-scroll"><table class="data-table"><thead><tr><th>ME</th><th>Entity ID</th><th>VID</th><th>'+bi('Правило / направление','Rule / direction')+'</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+r.class+'</td><td>'+esc(r.entity)+'</td><td>'+r.vid+(r.vid>4094?' · '+bi('специальное значение','special value'):'')+'</td><td>'+esc(r.rule)+'</td></tr>').join('')+'</tbody></table></div>':'<p class="muted">'+bi('VLAN не распознаны в доступном выводе. Это не означает отсутствие VLAN.','No VLANs recognised in the available output. This does not mean VLANs are absent.')+'</p>';
 const classes={84:'VLAN Tagging Filter',171:'Extended VLAN Tagging',78:'VLAN Tagging Operation',79:'MAC Bridge Port Filter',268:'GEM Port CTP',262:'T-CONT',277:'Priority Queue',7:'Software Image',257:'ONU2-G'};
 return card(bi('VLAN в текущей таблице OMCI','VLANs in the current OMCI table'),bi('VID 4095 и другие специальные значения не являются обычным сервисным VLAN.','VID 4095 and other special values are not ordinary service VLANs.'),vlan)+card(bi('GEM, T-CONT и другие объекты','GEM, T-CONT and other objects'),bi('Точные атрибуты сохранены в исходном выводе.','Exact attributes are preserved in the raw output.'),[268,262,277].map(cls=>'<h3>'+classes[cls]+' · ME '+cls+'</h3>'+mibRecords(data['me_'+cls]).map(r=>'<dl class="details">'+detail('Entity ID',r.id)+detail(bi('Атрибуты','Attributes'),r.lines.join('\n'))+'</dl>').join('')).join(''))+card(bi('Исходные данные','Raw data'),bi('Чтение не меняет настройки. Неподдерживаемые команды помечены READ_ERROR.','Reading does not change settings. Unsupported commands are marked READ_ERROR.'),Object.entries(classes).map(([cls,name])=>'<details><summary>ME '+cls+' · '+name+'</summary><pre>'+esc(data['me_'+cls]||bi('Нет данных','No data'))+'</pre></details>').join('')+'<details><summary>'+bi('Соединения OMCI','OMCI connections')+'</summary><pre>'+esc(data.connections||'—')+'</pre></details>'+[84,171].map(cls=>'<details><summary>'+bi('Снимок до первого изменения модом','Snapshot before the first mod change')+' · ME '+cls+'</summary><pre>'+esc(data['baseline_'+cls]||bi('Снимок отсутствует','Snapshot unavailable'))+'</pre></details>').join(''));}
function diagnostics(){return header(bi('Диагностика PON / OMCI','PON / OMCI diagnostics'),bi('Регистрация, оптика и реальные правила передачи трафика.','Registration, optics and actual traffic rules.'))+liveCard()+card(bi('Данные от OLT и локальные изменения','OLT data and local changes'),bi('OMCI доступен после обмена с OLT; до O5 таблицы могут быть пустыми.','OMCI requires OLT exchange; tables may be empty before O5.'),'<p>'+bi('Текущая MIB содержит действующие правила и может включать локальные изменения. Снимок до первого запуска VLAN-мода помогает сравнить их; он не отслеживает каждое последующее обновление OLT.','The current MIB contains effective rules and may include local changes. A snapshot before the first VLAN mod run helps compare them; it does not track every later OLT update.')+'</p><dl class="details">'+detail(bi('Сохранённый источник VLAN','Saved VLAN source'),state.VLAN_CFG_TYPE==='0'?bi('Автоматически · OLT','Automatic · OLT'):bi('Ручной','Manual'))+detail(bi('Сохранённый VLAN-мод','Saved VLAN mod'),state.MOD_VLAN)+'</dl><div class="actions"><button class="button secondary" id="read-omci">'+bi('Прочитать таблицы OMCI','Read OMCI tables')+'</button><button class="button" id="export-diag">'+bi('Скачать диагностику без паролей','Download diagnostics without passwords')+'</button></div><p id="diag-status" class="muted" role="status"></p>')+card(bi('История регистрации','Registration history'),bi('Переходы O1–O7 за время открытия панели; краткие переходы между опросами могут быть пропущены.','O1–O7 transitions while the panel is open; brief transitions between reads can be missed.'),'<div id="pon-history"></div>')+'<div id="omci-tables">'+(Object.keys(fullDiagnostic).length?diagnosticTables(fullDiagnostic):'')+'</div>';}
const publicDiagnosticKeys=['panel_version','firmware','OMCI_OLT_MODE','OMCI_TM_OPT','OMCI_FAKE_OK','OMCC_VER','OMCI_SW_VER1','OMCI_SW_VER2','sw_custom_version0','sw_custom_version1','VLAN_CFG_TYPE','VLAN_MANU_MODE','VLAN_MANU_TAG_VID','VLAN_MANU_TAG_PRI','LAN_SPEED_MODE','sw_active','sw_commit','sw_version0','sw_version1','pending','pending_keys','LOID_MIRROR_OK','MOD_SPEED','MOD_SWVER','MOD_VLAN','MOD_VLANS','MOD_ENTITIES','MOD_FWDOP','MOD_PAIRS'];
function safeDiagnostic(data){const raw={};for(const [key,val] of Object.entries(data)){if(/^(me_\d+|baseline_\d+|optic_[\w-]+|pon_state|uptime|sampled_uptime|memory|link_actual|auth_uptime|loid_auth|mods_status|mods_log|baseline_uptime|connections|collection_seconds|firmware_status|firmware_phase|firmware_error|firmware_log)$/.test(key))raw[key]=String(val).split('\n').map(line=>/password|passwd|pwd|ploam|serial|loid\s*[:=]|mac_key|csrf|challenge|(?:[0-9a-f]{2}:){5}[0-9a-f]{2}/i.test(line)?'[redacted]':line).join('\n');}
 return {format:'odi-diagnostics-v1',captured:new Date().toISOString(),scope:'Host UI capture; current MIB may contain local changes; no passwords or ONU serial/MAC settings',settings:Object.fromEntries(publicDiagnosticKeys.filter(k=>Object.hasOwn(state,k)).map(k=>[k,state[k]])),readings:raw,pon_history:ponHistory};}
function bindDiagnostics(){const read=document.getElementById('read-omci'),exp=document.getElementById('export-diag');async function collect(download){if(busy||read.disabled)return;read.disabled=true;exp.disabled=true;clearTimeout(liveTimer);while(liveReading){await new Promise(resolve=>setTimeout(resolve,100));if(!read.isConnected)return;}liveReading=true;clearTimeout(liveTimer);const status=document.getElementById('diag-status');status.textContent=bi('Чтение таблиц… это может занять до минуты.','Reading tables… this may take up to a minute.');try{const data=preview?{pon_state:'preview; no device data'}:await readApi('diagnostics',65000);fullDiagnostic=data;if(!preview){live=data;liveAt=Date.now()-Number(data.collection_seconds||0)*1000;liveError='';paintLive();}const tables=document.getElementById('omci-tables');if(tables)tables.innerHTML=diagnosticTables(data);status.textContent=bi('Таблицы прочитаны. Пустые и неподдерживаемые результаты сохранены в исходном выводе.','Tables read. Empty and unsupported results are preserved in the raw output.');if(download)downloadJSON('ODI-diagnostics.json',safeDiagnostic(data));}catch(e){status.textContent=e.message;toast(e.message,true);}finally{liveReading=false;read.disabled=false;exp.disabled=false;restartLive();}}
 if(read)read.onclick=()=>collect(false);if(exp)exp.onclick=()=>collect(true);}
function modRuntime(){return card(bi('Фактическая работа модов','Mod runtime status'),bi('Статус текущей загрузки и последние результаты; сохранённые переключатели показаны отдельно.','Status of this boot and recent results; saved switches are shown separately.'),'<div id="mod-runtime"></div><details><summary>'+bi('Журнал модов','Mod log')+'</summary><pre id="mod-log"></pre></details><p class="muted">'+bi('Выключение мода применяется после перезагрузки. Исходные версии OMCI сохраняются перед первой подменой этой версией панели.','Disabling a mod takes effect after reboot. Original OMCI versions are saved before this panel version first replaces them.')+'</p><div class="actions"><button class="button secondary" id="restore-versions" '+(preview||state.MOD_SWVER!=='0'||state.OMCI_OLT_MODE!=='3'||!state.original_OMCI_SW_VER1||!state.original_OMCI_SW_VER2?'disabled':'')+'>'+bi('Восстановить исходные версии OMCI','Restore original OMCI versions')+'</button></div>');}
function paintModRuntime(){const el=document.getElementById('mod-runtime');if(el){const raw=live.mods_status||state.mods_status||'',parts=Object.fromEntries(raw.split('\n').map(s=>s.split('='))),age=Number(live.sampled_uptime)-Number(parts.heartbeat);el.innerHTML='<pre>'+esc(raw||bi('Результаты ещё не записаны.','No runtime results recorded yet.'))+'</pre><p>'+esc(parts.vlan&&parts.vlan!=='off'?(Number.isFinite(age)&&age<45?bi('Цикл недавно обновил статус.','The loop updated its status recently.'):bi('Статус цикла устарел.','Loop status is stale.')):bi('VLAN-цикл выключен; исправление скорости выполняется однократно.','VLAN loop is off; the speed fix runs once.'))+'</p>';document.getElementById('mod-log').textContent=live.mods_log||state.mods_log||'—';}}
async function restoreVersions(){if(preview||busy)return;if(!await confirmAction(bi('Восстановить версии OMCI?','Restore OMCI versions?'),bi('Версии из резервной записи будут восстановлены, пользовательские версии очищены. Для применения потребуется перезагрузка.','Backed-up versions will be restored and custom versions cleared. Reboot is required to apply.')))return;busy=true;try{await api('restore_versions');busy=false;await load();toast(bi('Исходные версии восстановлены и проверены.','Original versions restored and verified.'));}catch(e){busy=false;toast(e.message,true);}}
