'use strict';
const layoutKey='odi-panel-layout';
let interfaceLayout='compact';
const rootSections=[['overview','Состояние','M3 12h3l3-8 4 16 3-8h5'],['identity','PON / ONU','M4 4h16v16H4z M8 8h8 M8 12h8 M8 16h5'],['wan','Сеть','M12 3v6 M5 16v5 M19 16v5 M5 16h14v-4H5z M9 3h6v6H9z'],['diagnostics','Диагностика','M4 19V5 M4 19h16 M8 15v-4 M12 15V7 M16 15v-6'],['mods','Моды','M12 3v4 M12 17v4 M3 12h4 M17 12h4 M8 8h8v8H8z'],['profiles','Профили','M4 5h7l2 3h7v12H4z M8 12h8 M8 16h5'],['firmware','Прошивка','M4 4h16v16H4z M8 4v6h8V4 M8 20v-6h8v6'],['native-password','Система','M12 3v3 M12 18v3 M3 12h3 M18 12h3 M6 6l2 2 M16 16l2 2 M6 18l2-2 M16 8l2-2 M16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0']];
function sectionRoot(){if(['wan','vlan','link'].includes(tab)||location.hash==='#native-lan')return 'wan';if(tab==='native'){const id=location.hash.slice(8);if(['status','pon'].includes(id))return 'overview';if(['arp','ping','stats','pon-stats'].includes(id))return 'diagnostics';return 'native-password';}return tab;}
function paintSectionNav(){const root=sectionRoot(),nativeEntry=id=>nativePages.find(p=>p[0]===id),nativeTab=id=>{const p=nativeEntry(id);return p?['native-'+id,p[1]]:null;};let entries=[];
 if(root==='overview')entries=[['overview','Сводка'],nativeTab('status'),nativeTab('pon')];
 if(root==='wan')entries=[nativeWan.pon||nativeWan.mode?['wan',nativeWan.pon?'PON WAN':'Режим WAN']:null,['vlan','VLAN'],['link','SFP-порт'],nativeTab('lan')];
 if(root==='diagnostics')entries=[['diagnostics','PON / OMCI'],nativeTab('arp'),nativeTab('ping'),nativeTab('stats'),nativeTab('pon-stats')];
 if(root==='native-password')entries=[nativeTab('password'),nativeTab('timer'),['native-recovery','Восстановление доступа'],...nativePages.filter(p=>p[3]==='Штатные разделы').map(p=>['native-'+p[0],p[1]])];
 const nav=document.getElementById('section-nav');nav.innerHTML=entries.filter(Boolean).map(([id,label])=>'<a href="#'+esc(id)+'" '+(id.startsWith('native-')?'data-native="'+esc(id.slice(7))+'"':'data-tab="'+esc(id)+'"')+' aria-current="'+((location.hash||'#overview')==='#'+id?'page':'false')+'">'+esc(label)+'</a>').join('');nav.hidden=!nav.children.length;
 document.querySelectorAll('#native-nav a').forEach(a=>{const active=a.hash==='#'+root;a.classList.toggle('active',active);a.setAttribute('aria-current',active?'page':'false');});ODILang.apply(nav);
}
function setInterfaceLayout(next,persist=false){interfaceLayout=next==='diagnostic'?'diagnostic':'compact';document.body.dataset.layout=interfaceLayout;for(const b of document.querySelectorAll('[data-layout-choice]'))b.setAttribute('aria-pressed',String(b.dataset.layoutChoice===interfaceLayout));document.getElementById('diagnostic-rail').hidden=interfaceLayout!=='diagnostic';if(persist)try{localStorage.setItem(layoutKey,interfaceLayout);}catch(_){}paintShellTelemetry();restartLive();}
function initLayout(){let saved;try{saved=localStorage.getItem(layoutKey);}catch(_){}setInterfaceLayout(saved);for(const b of document.querySelectorAll('[data-layout-choice]'))b.onclick=()=>setInterfaceLayout(b.dataset.layoutChoice,true);window.addEventListener('storage',e=>{if(e.key===layoutKey)setInterfaceLayout(e.newValue);});window.addEventListener('odi-language-change',paintShellTelemetry);setInterval(()=>{if(!document.hidden)paintShellTelemetry();},5000);}
function paintShellTelemetry(){const stage=ponStage(live.pon_state),fresh=Boolean(liveAt&&Date.now()-liveAt<25000&&!liveError),tone=fresh?(stage==='O5'?'online':stage?'waiting':'unknown'):'unknown',put=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value;};
 document.getElementById('signal-strip').dataset.tone=tone;document.getElementById('diagnostic-rail').dataset.tone=tone;
 const stamp=preview?bi('Предпросмотр · нет чтения устройства','Preview · no device readings'):liveError?bi('Ошибка чтения','Read error'):liveAt?(fresh?bi('Обновлено: ','Updated: '):bi('Устарело: ','Stale: '))+new Date(liveAt).toLocaleTimeString():bi('Нет чтений','No readings');
 put('strip-stage',stage||'—');put('strip-rx',numericMetric(live['optic_rx-power']));put('strip-tx',numericMetric(live['optic_tx-power']));put('strip-temp',numericMetric(live.optic_temperature));put('strip-stamp',stamp);put('rail-stage',stage||'—');put('rail-fresh',fresh?bi('АКТУАЛЬНО','LIVE'):bi('НЕТ АКТУАЛЬНЫХ ДАННЫХ','NO FRESH DATA'));put('rail-state-label',stage&&!fresh?bi('Последнее чтение','Last reading'):stage?(stage==='O5'?bi('Регистрация активна','Registration active'):bi('Регистрация не завершена','Registration incomplete')):bi('Нет данных','No data'));put('rail-hint',preview?bi('На устройстве здесь появятся текущая регистрация и оптические измерения.','Device registration and optical readings will appear here.'):stageHint(stage));put('rail-stamp',stamp);
 document.getElementById('rail-track').innerHTML=Array.from({length:7},(_,i)=>'<span class="'+(stage==='O'+(i+1)?'current':'')+'">O'+(i+1)+'</span>').join('');
 document.getElementById('rail-optics').innerHTML=[['RX',numericMetric(live['optic_rx-power'])],['TX',numericMetric(live['optic_tx-power'])],[bi('Температура','Temperature'),numericMetric(live.optic_temperature)],[bi('Напряжение','Voltage'),numericMetric(live.optic_voltage)],[bi('Ток лазера','Laser bias'),numericMetric(live['optic_bias-current'])],[bi('Режим порта','Port mode'),live.link_actual||state.link_actual||'—']].map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('');
 put('rail-history-count',String(ponHistory.length));document.getElementById('rail-history').innerHTML=ponHistory.length?'<ol class="transition-list">'+ponHistory.slice(-12).reverse().map(x=>'<li><time>'+esc(x.time)+'</time><strong class="'+(x.stage==='O5'?'registered':'')+'">'+esc(x.stage)+'</strong></li>').join('')+'</ol>':'<p class="muted">'+bi('Переходы появятся после чтения.','Transitions appear after reading.')+'</p>';
}
