'use strict';
const profileKeys=['GPON_SN','GPON_PLOAM_FORMAT','GPON_PLOAM_PASSWD','LOID','LOID_PASSWD','PON_VENDOR_ID','GPON_ONU_MODEL','HW_HWVER','HW_SERIAL_NO','OUI','OMCI_OLT_MODE','OMCI_TM_OPT','OMCI_FAKE_OK','OMCC_VER','ELAN_MAC_ADDR','MAC_KEY','VLAN_CFG_TYPE','VLAN_MANU_MODE','VLAN_MANU_TAG_VID','VLAN_MANU_TAG_PRI','LAN_SPEED_MODE','sw_custom_version0','sw_custom_version1'];
const modProfileKeys=['MOD_SPEED','MOD_SWVER','MOD_VLAN','MOD_VLANS','MOD_ENTITIES','MOD_FWDOP','MOD_PAIRS'];
const privateProfileKeys=new Set(['GPON_SN','GPON_PLOAM_PASSWD','LOID','LOID_PASSWD','HW_SERIAL_NO','ELAN_MAC_ADDR','MAC_KEY']);
let importedProfile=null;
function validateProfile(key,val){if(typeof val!=='string'||! /^[\x20-\x7e]*$/.test(val))return false;const patterns={GPON_SN:/^[A-Za-z0-9]{4}[0-9a-fA-F]{8}$/,GPON_PLOAM_FORMAT:/^[01]$/,GPON_PLOAM_PASSWD:/^[0-9a-fA-F]{20}$/,PON_VENDOR_ID:/^[A-Za-z0-9]{4}$/,OUI:/^[0-9a-fA-F]{6}$/,OMCI_OLT_MODE:/^[0-3]$/,OMCI_TM_OPT:/^[0-2]$/,OMCI_FAKE_OK:/^[01]$/,OMCC_VER:/^(128|129|130|131|132|133|134|150|160|161|162|163|176|177|178|179)$/,ELAN_MAC_ADDR:/^[0-9a-fA-F]{12}$/,MAC_KEY:/^[0-9a-fA-F]{32}$/,VLAN_CFG_TYPE:/^[01]$/,VLAN_MANU_MODE:/^[01]$/,VLAN_MANU_TAG_VID:/^[1-9][0-9]{0,3}$/,VLAN_MANU_TAG_PRI:/^[0-7]$/,LAN_SPEED_MODE:/^[1-7]$/,MOD_SPEED:/^[01]$/,MOD_SWVER:/^[01]$/,MOD_VLAN:/^(off|tag|fwdop)$/,MOD_FWDOP:/^0x[0-9a-fA-F]{2}$/,MOD_ENTITIES:/^(?:0x[0-9a-fA-F]{1,4}(?: 0x[0-9a-fA-F]{1,4})*)?$/,MOD_PAIRS:/^(?:0x[0-9a-fA-F]{1,4}:0x[0-9a-fA-F]{2}(?:,0x[0-9a-fA-F]{1,4}:0x[0-9a-fA-F]{2})*)?$/,MOD_VLANS:/^(?:[1-9][0-9]{0,3}(?: [1-9][0-9]{0,3})*)?$/};
 if(patterns[key])return patterns[key].test(val)&&(key!=='VLAN_MANU_TAG_VID'||+val<=4094)&&(!key.startsWith('MOD_')||val.length<=120)&&(key!=='MOD_VLANS'||val===''||val.split(' ').every(x=>+x<=4094));
 const sizes={GPON_ONU_MODEL:20,HW_HWVER:14,HW_SERIAL_NO:64,LOID:28,LOID_PASSWD:12,sw_custom_version0:14,sw_custom_version1:14};return Object.hasOwn(sizes,key)&&val.length<=sizes[key]&&(/^[A-Za-z0-9._:/+@ -]+$/.test(val)||val===''&&['LOID','LOID_PASSWD','sw_custom_version0','sw_custom_version1'].includes(key));
}
function parseProfile(text){let values={},metadata={},source='JSON',suggestions=[];
 if(text.trimStart().startsWith('<')){source='Realtek XML';const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror')||doc.documentElement.nodeName!=='Config')throw new Error(bi('Неверный XML конфигурации.','Invalid configuration XML.'));
  for(const dir of doc.querySelectorAll('Config > Dir'))if(['MIB_TABLE','HW_MIB_TABLE'].includes(dir.getAttribute('Name')))for(const el of dir.children)if(el.nodeName==='Value')values[el.getAttribute('Name')]=el.getAttribute('Value')??el.textContent;
  for(const [old,key] of [['OMCI_SW_VER1','sw_custom_version0'],['OMCI_SW_VER2','sw_custom_version1']])if(values[old]){values[key]=values[old];suggestions.push(key);}delete values.OMCI_SW_VER1;delete values.OMCI_SW_VER2;
 }else if(/^\s*(?:#.*\n\s*)?config\s/m.test(text)){source='OpenWrt / Lantiq';const u={};for(const line of text.split('\n')){const m=line.match(/^\s*option\s+'?(\w+)'?\s+'([^']*)'\s*$/);if(m)u[m[1]]=m[2];}
  if(u.nSerial&&/^[0-9a-fA-F]{16}$/.test(u.nSerial)){const vendor=u.nSerial.slice(0,8).replace(/../g,x=>String.fromCharCode(parseInt(x,16)));values.GPON_SN=vendor+u.nSerial.slice(8).toUpperCase();}
  if(u.nPassword){const bytes=u.nPassword.trim().split(/\s+/);if(bytes.length===10&&bytes.every(x=>/^0x[0-9a-fA-F]{2}$/.test(x))){values.GPON_PLOAM_PASSWD=bytes.map(x=>x.slice(2)).join('').toUpperCase();values.GPON_PLOAM_FORMAT='0';}}
  for(const [from,to] of [['vendor_id','PON_VENDOR_ID'],['equipment_id','GPON_ONU_MODEL'],['ont_version','HW_HWVER'],['omci_loid','LOID'],['omci_lpwd','LOID_PASSWD']])if(Object.hasOwn(u,from))values[to]=u[from].replace(/(?:\\0)+$/,'');
  suggestions.push('HW_HWVER','LOID','LOID_PASSWD');
  for(const k of ['uvlan','iopmask','mib_customized','ignore_rx_loss','disable_rx_los_status','mib_file'])if(Object.hasOwn(u,k))metadata[k]=u[k];
  metadata.note='Lantiq parameters and optical calibration are not restored on Realtek. uvlan is a reference, not evidence of an OLT VLAN. ont_version is suggested as OMCI hardware version; verify with OLT.';
 }else{const obj=JSON.parse(text);if(obj.format!=='odi-profile-v1'||!obj.settings||Array.isArray(obj.settings))throw new Error(bi('Неподдерживаемый формат профиля.','Unsupported profile format.'));if(obj.platform&&obj.platform!=='RTL9601D/SFU-240408')throw new Error(bi('Профиль другой платформы. Используйте исходную конфигурацию для сравнения.','Profile targets another platform. Use the original configuration for comparison.'));values={...obj.settings,...obj.mods};metadata=obj.reference||{};source=obj.source||source;suggestions=Array.isArray(obj.suggestions)?obj.suggestions:[];}
 const settings={},mods={},rejected=[];for(const [key,val] of Object.entries(values)){if(!profileKeys.includes(key)&&!modProfileKeys.includes(key))continue;if(!validateProfile(key,val)){rejected.push(key);continue;}(modProfileKeys.includes(key)?mods:settings)[key]=val;}
 if(!Object.keys(settings).length&&!Object.keys(mods).length)throw new Error(bi('Поддерживаемые параметры не найдены.','No supported parameters found.'));return {settings,mods,metadata,source,suggestions,rejected};
}
async function profileFileText(file){if(file.size>2097152)throw new Error(bi('Файл профиля слишком большой.','Profile file too large.'));if(!file.name.toLowerCase().endsWith('.gz'))return await file.text();if(typeof DecompressionStream==='undefined')throw new Error(bi('Этот браузер не распаковывает GZ. Выберите подготовленный JSON-профиль или файл gpon из архива.','This browser cannot unpack GZ. Select the prepared JSON profile or the gpon file from the archive.'));
 const reader=file.stream().pipeThrough(new DecompressionStream('gzip')).getReader(),chunks=[];let total=0;for(;;){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>2097152){await reader.cancel();throw new Error(bi('Распакованный архив слишком большой.','Unpacked archive too large.'));}chunks.push(value);}const bytes=new Uint8Array(total);let at=0;for(const chunk of chunks){bytes.set(chunk,at);at+=chunk.length;}
 const decoder=new TextDecoder(),found=[];for(let offset=0;offset+512<=bytes.length;){const header=bytes.slice(offset,offset+512);if(header.every(b=>b===0))break;const name=decoder.decode(header.slice(0,100)).split('\0')[0],sizeText=decoder.decode(header.slice(124,136)).replace(/\0/g,'').trim();if(!/^[0-7]+$/.test(sizeText))throw new Error('Invalid TAR header');const size=parseInt(sizeText,8),type=header[156];if(offset+512+size>bytes.length)throw new Error('Truncated TAR');if(name.replace(/^\.\//,'')==='etc/config/gpon'&&(type===0||type===48))found.push(decoder.decode(bytes.slice(offset+512,offset+512+size)));offset+=512+Math.ceil(size/512)*512;}
 if(found.length!==1)throw new Error(bi('В архиве не найден единственный файл etc/config/gpon.','The archive must contain exactly one etc/config/gpon file.'));return found[0];
}
function profileControls(){return card(bi('Профиль и резервная копия панели','Profile and panel backup'),bi('Сравнение выполняется локально. Импорт не записывает параметры до подтверждения.','Comparison runs locally. Import writes nothing until confirmation.'),'<div class="grid"><div class="field"><label for="profile-file">'+bi('Рабочий профиль: GZ, JSON, XML или UCI gpon','Working profile: GZ, JSON, XML or UCI gpon')+'</label><input id="profile-file" type="file" accept=".gz,.json,.xml,*/*"></div><div><p class="muted">'+bi('Резервная копия включает параметры панели, моды и пользовательские версии. Штатная копия отдельно сохраняет основные таблицы MIB. Оптические калибровки и прошивка сюда не входят.','The backup includes panel settings, mods and custom versions. The factory backup separately saves core MIB tables. Optical calibration and firmware are excluded.')+'</p><label class="check"><input type="checkbox" id="profile-secrets">'+bi('Включить SN, MAC и пароли в скачиваемую копию','Include SN, MAC and passwords in the downloaded backup')+'</label><button class="button secondary" id="export-profile">'+bi('Скачать профиль панели','Download panel profile')+'</button></div></div><div id="profile-diff"></div>');}
function profileDisplay(key,val,reveal){return privateProfileKeys.has(key)&&!reveal?(val===''?bi('Пусто','Empty'):bi('Скрыто','Hidden')):String(val??'—');}
function paintProfile(){const root=document.getElementById('profile-diff');if(!root||!importedProfile)return;const p=importedProfile,reveal=document.getElementById('profile-reveal')?.checked||false;
 root.innerHTML='<h3 class="profile-heading">'+bi('Сравнение с текущей конфигурацией','Comparison with current configuration')+' · '+esc(p.source)+'</h3><p class="muted">'+bi('GPON SN — идентификатор регистрации; HW_SERIAL_NO — отдельный серийный номер OMCI; Vendor ID и MAC не заменяют GPON SN. Выберите только проверенные соответствия.','GPON SN identifies registration; HW_SERIAL_NO is a separate OMCI serial. Vendor ID and MAC do not replace GPON SN. Select only verified mappings.')+'</p><label class="check"><input type="checkbox" id="profile-reveal" '+(reveal?'checked':'')+'>'+bi('Показать личные значения в сравнении','Show private values in comparison')+'</label><div class="table-scroll"><table class="data-table"><thead><tr><th>'+bi('Перенос','Apply')+'</th><th>'+bi('Параметр','Parameter')+'</th><th>'+bi('Сейчас','Current')+'</th><th>'+bi('В профиле','Profile')+'</th><th>'+bi('Статус','Status')+'</th></tr></thead><tbody>'+Object.entries({...p.settings,...p.mods}).map(([key,val])=>{const supported=value(key)!==null,diff=state[key]!==val,suggest=p.suggestions.includes(key);return '<tr><td><input type="checkbox" data-profile-key="'+key+'" '+(supported&&diff?'':'disabled')+' '+(supported&&diff&&!suggest?'checked':'')+'></td><td class="mono">'+key+'</td><td>'+esc(profileDisplay(key,state[key],reveal))+'</td><td>'+esc(profileDisplay(key,val,reveal))+'</td><td>'+esc(!supported?bi('Недоступен','Unavailable'):!diff?bi('Совпадает','Matches'):suggest?bi('Проверьте соответствие','Verify mapping'):bi('Отличается','Different'))+'</td></tr>';}).join('')+'</tbody></table></div>'+(p.rejected.length?'<p class="banner warn">'+bi('Невалидные поля исключены: ','Invalid fields excluded: ')+esc(p.rejected.join(', '))+'</p>':'')+(Object.keys(p.metadata).length?'<details><summary>'+bi('Параметры исходной платформы · только справка','Original platform parameters · reference only')+'</summary><pre>'+esc(JSON.stringify(p.metadata,null,2))+'</pre></details>':'')+'<div class="actions profile-actions"><button class="button" id="apply-profile" '+(preview?'disabled':'')+'>'+bi('Сохранить выбранные параметры','Save selected parameters')+'</button></div>';
 document.getElementById('profile-reveal').onchange=()=>{const choices=Array.from(root.querySelectorAll('[data-profile-key]')).filter(el=>el.checked).map(el=>el.dataset.profileKey);paintProfile();for(const el of root.querySelectorAll('[data-profile-key]'))el.checked=choices.includes(el.dataset.profileKey);};document.getElementById('apply-profile').onclick=applyProfile;
}
async function applyProfile(){if(preview||busy||!importedProfile)return;if(dirty){toast(bi('Сохраните или отмените изменения формы перед импортом.','Save or discard form changes before import.'),true);return;}const settings={},mods={};for(const el of document.querySelectorAll('[data-profile-key]:checked')){const k=el.dataset.profileKey;if(Object.hasOwn(importedProfile.settings,k))settings[k]=importedProfile.settings[k];else mods[k]=importedProfile.mods[k];}
 if(Object.hasOwn(settings,'GPON_PLOAM_PASSWD'))settings.GPON_PLOAM_FORMAT=importedProfile.settings.GPON_PLOAM_FORMAT||'0';
 if(Object.hasOwn(settings,'ELAN_MAC_ADDR')&&!Object.hasOwn(settings,'MAC_KEY')){toast(bi('Для переноса MAC выберите соответствующий MAC_KEY.','Select the matching MAC_KEY to apply a MAC address.'),true);return;}
 if(Object.keys(settings).some(k=>k.startsWith('sw_custom_version'))&&String(settings.OMCI_OLT_MODE??state.OMCI_OLT_MODE)!=='3'){toast(bi('Пользовательские версии требуют режима OMCI 3.','Custom versions require OMCI mode 3.'),true);return;}
 if(!Object.keys(settings).length&&!Object.keys(mods).length)return;
 if(!await confirmAction(bi('Сохранить выбранные параметры профиля?','Save selected profile parameters?'),bi('Будут изменены только отмеченные поля. Режим порта может изменить доступ к ONU после перезагрузки. Настройки и моды сохраняются отдельными операциями; их результаты будут показаны отдельно.','Only selected fields will change. Port mode can affect access after reboot. Settings and mods are saved as separate operations; each result is reported separately.')))return;
 busy=true;let saved=false;try{if(Object.keys(settings).length){await api('save',settings);saved=true;}if(Object.keys(mods).length)await api('mods',Object.fromEntries(modProfileKeys.map(k=>[k,Object.hasOwn(mods,k)?mods[k]:state[k]])));busy=false;await load();toast(bi('Выбранные параметры сохранены и проверены. Перезагрузите отдельно.','Selected settings saved and verified. Reboot separately.'));}catch(e){busy=false;toast((saved?bi('Параметры сохранены; моды не подтверждены. ','Settings saved; mods not confirmed. '):'')+e.message,true);}
}
function bindProfiles(){const input=document.getElementById('profile-file');if(input)input.onchange=async()=>{try{if(!input.files[0])return;importedProfile=parseProfile(await profileFileText(input.files[0]));paintProfile();}catch(e){importedProfile=null;document.getElementById('profile-diff').textContent=e.message;toast(e.message,true);}};
 const button=document.getElementById('export-profile');if(button)button.onclick=async()=>{const secrets=document.getElementById('profile-secrets').checked;if(secrets&&!await confirmAction(bi('Скачать копию с личными данными?','Download a backup with private data?'),bi('Файл будет содержать серийники, MAC и пароли. Храните его в безопасном месте и не публикуйте.','The file will contain serials, MAC and passwords. Store it securely and do not publish it.')))return;downloadJSON('ODI-panel-profile'+(secrets?'-PRIVATE':'')+'.json',{format:'odi-profile-v1',platform:'RTL9601D/SFU-240408',source:'ODI Panel '+(state.panel_version||document.querySelector('meta[name=odi-panel-version]')?.content||'unknown'),captured:new Date().toISOString(),contains_secrets:secrets,settings:Object.fromEntries(profileKeys.filter(k=>value(k)!==null&&(secrets||!privateProfileKeys.has(k))).map(k=>[k,state[k]])),mods:Object.fromEntries(modProfileKeys.map(k=>[k,state[k]])),reference:{original_OMCI_SW_VER1:state.original_OMCI_SW_VER1,original_OMCI_SW_VER2:state.original_OMCI_SW_VER2},scope:'Panel settings only; not firmware or optical calibration. Original OMCI values are reference data, not an automatic restore instruction.'});};paintProfile();}
function profiles(){return header(bi('Профили и резервная копия','Profiles and backup'),bi('Перенос с рабочего ONU и сравнение перед сохранением.','Transfer from a working ONU and compare before saving.'))+profileControls()+card(bi('Штатная резервная копия','Factory backup'),bi('Сохраняет основные таблицы конфигурации. Файлы модов и пользовательские версии дополнительно сохраните кнопкой выше.','Saves core configuration tables. Also use the button above to back up mods and custom versions.'),nativeEmbed('/saveconf.asp',bi('Обслуживание устройства','Device maintenance')));}
