'use strict';
let renderedHash='',navigationPending=false;
function showAuth(){const el=document.getElementById('connection');el.textContent=bi('Сессия истекла','Session expired');el.className='status';let bar=document.getElementById('auth-expired');if(!bar){bar=document.createElement('div');bar.id='auth-expired';bar.className='banner warn';bar.innerHTML='<span>'+bi('Требуется авторизация. Несохранённые поля остаются открытыми.','Sign-in required. Unsaved fields remain open.')+'</span><a class="button secondary" href="/admin/login.asp" id="sign-in">'+bi('Войти снова','Sign in again')+'</a><button class="button secondary" id="retry-auth">'+bi('Проверить вход','Check sign-in')+'</button>';document.getElementById('main').prepend(bar);bar.querySelector('#sign-in').onclick=()=>{try{sessionStorage.setItem('odi-panel-return',renderedHash||'#overview');}catch(_){} };bar.querySelector('#retry-auth').onclick=async()=>{try{await api();bar.remove();el.textContent=bi('Вход подтверждён','Sign-in confirmed');el.className='status ready';}catch(e){toast(e.message,true);}};}}
function formStatus(){const pending=new Set((state.pending_keys||'').split('\n').filter(Boolean));for(const form of document.querySelectorAll('[data-settings]')){const changed=Array.from(form.elements).some(el=>(el.name&&!el.disabled&&controlChanged(el))||el.dataset.edited==='1');form.classList.toggle('has-draft',changed);const info=form.querySelector('.card-foot small');if(info)info.textContent=changed?bi('Есть несохранённые изменения.','Unsaved changes.'):Array.from(form.elements).some(el=>((el.name&&pending.has(el.name))||(el.name.startsWith('MOD_')&&pending.has('MODS'))))?bi('Сохранено и проверено; ожидает перезагрузки.','Saved and verified; reboot pending.'):bi('Показаны сохранённые настройки. Фактические значения смотрите в диагностике.','Saved settings shown. Check diagnostics for actual values.');for(const el of form.querySelectorAll('[name]')){let badge=el.closest('.field')?.querySelector('.field-status');if(!badge&&el.closest('.field')){badge=document.createElement('small');badge.className='field-status';el.closest('.field').append(badge);}if(badge){badge.hidden=!el.disabled&&!controlChanged(el)&&!pending.has(el.name);badge.textContent=el.disabled?bi('Недоступен или не используется в этом режиме','Unavailable or unused in this mode'):controlChanged(el)?bi('Не сохранено','Unsaved'):pending.has(el.name)?bi('Сохранено · ожидает перезагрузки','Saved · reboot pending'):bi('Сохранённое значение','Saved value');}}}
}
function bindUX(){paintSectionNav();renderedHash=location.hash||'#overview';formStatus();bindDiagnostics();bindProfiles();restartLive();const restore=document.getElementById('restore-versions');if(restore)restore.onclick=restoreVersions;document.body.classList.remove('menu-open');document.getElementById('menu-toggle').setAttribute('aria-expanded','false');}
async function navigateChanged(){if(navigationPending)return;const next=location.hash||'#overview';if(next===renderedHash)return;if(busy){history.replaceState(null,'',renderedHash||'#overview');return;}const frame=document.querySelector('.native-frame');try{if(frame?.contentWindow.nativeDirty)dirty=true;}catch(_){}
 if(dirty){history.replaceState(null,'',renderedHash||'#overview');navigationPending=true;const proceed=await confirmAction('Перейти без сохранения?','Несохранённые изменения на этой странице будут потеряны.');navigationPending=false;if(!proceed)return;dirty=false;try{if(frame?.contentWindow)frame.contentWindow.nativeDirty=false;}catch(_){}history.replaceState(null,'',next);}if(Object.keys(state).length||next.startsWith('#native-'))render();
}
function initUX(){initLayout();document.getElementById('menu-toggle').onclick=()=>{document.body.classList.toggle('menu-open');document.getElementById('menu-toggle').setAttribute('aria-expanded',String(document.body.classList.contains('menu-open')));};document.getElementById('logout').onclick=async e=>{e.preventDefault();if(busy)return;if(dirty&&!await confirmAction('Перейти без сохранения?','Несохранённые изменения на этой странице будут потеряны.'))return;dirty=false;location.href='/admin/logout.asp';};
 document.getElementById('main').addEventListener('input',formStatus);document.getElementById('main').addEventListener('change',formStatus);try{const saved=sessionStorage.getItem('odi-panel-return');if(saved&&/^#[a-z0-9-]+$/.test(saved)){history.replaceState(null,'',saved);sessionStorage.removeItem('odi-panel-return');}}catch(_){} }
