from pathlib import Path
import hashlib,json,zipfile
p=Path(__file__).resolve().parent;root=p.parent
from release import VERSION, sync_sources
sync_sources(check=True)
# Regenerate previews from current sources; do not package stale snapshots.
import runpy
runpy.run_path(str(p/'make_preview.py'))
archive=root/f'ODI-Panel-{VERSION}-RU-EN-SFU-240408.zip'
build=root/f'release-{VERSION}-sfu'
report=json.loads((build/'build-report.json').read_text())
assert report['panel_version']==VERSION and report['base_tag']=='SFU-240408'
image=next(build.glob('*.tar'))
with zipfile.ZipFile(archive,'w',zipfile.ZIP_DEFLATED) as z:
 z.write(image,image.name);checksum=hashlib.sha256(image.read_bytes()).hexdigest()+'  '+image.name
 z.write(build/'build-report.json','reports/sfu-build-report.json')
 z.write(build/'boa-patch-report.json','reports/sfu-boa-patch-report.json')
 z.write(p/f'README-{VERSION}.md','README-RU.md')
 # Private ISP reference: never in git; packaged only when present locally.
 huawei=root/'Huawei-working-reference-RU.md'
 if huawei.exists():z.write(huawei,'docs/05-HUAWEI-WORKING-PROFILE-RU.md')
 z.write(p/'preview.html','preview.html');z.write(p/'login-preview.html','login-preview.html')
 for f in sorted((p/'docs').glob('*.md')):z.write(f,'docs/'+f.name)
 for f in sorted((p/'src').rglob('*')):
  if f.is_file():z.write(f,'source/src/'+str(f.relative_to(p/'src')))
 for f in sorted((p/'upstream').rglob('*')):
  if f.is_file() and not (f.parent.name=='odi-tools' and f.suffix!='.json'):z.write(f,'source/upstream/'+str(f.relative_to(p/'upstream')))
 for f in sorted(p.iterdir()):
  if f.is_file() and f.name!='patch_build.py' and (f.suffix in ['.py','.cjs','.txt'] or f.name=='VERSION' or f.name in ['native-en.json','native-cn.json','native-preview.json']):z.write(f,'source/'+f.name)
 for n in ['patch_boa.py','test_patch.py','test_unicorn.py']:z.write(p/'hotfix'/n,'source/hotfix/'+n)
 z.write(p/'hotfix/patch-test-report.json','reports/sfu-boa-emulation.json')
 for n in ['localization-test-report.json','form-parity-report.json','mods-test-report.json','mods-ui-test-report.json','native-menu-test-report.json','native-frames-test-report.json','backend-test-report.json','mackey-test-report.json','layout-test-report.json','shared-loid-evidence.json','integration-test-report.json','firmware-test-report.json','firmware-ui-test-report.json','patch-inventory.json','translation-coverage.json','diagnostics-test-report.json','features17-test-report.json','modes18-test-report.json','version-test-report.json']:z.write(p/n,'reports/'+n)
 z.writestr('reports/validation-scope.json',json.dumps({
  'current_version':VERSION,
  'base':'ODI SFU V1.1.8-240408 (hardware tag X100SFP); tested on ODI DFP-34X-2IY2, hardware V08 with DDM',
  'build':'build.py from the factory M110_sfp_ODI_SFU_240408.tar (SHA256 79c5ce4e...); reproducible; every SquashFS entry not generated by the panel verified identical to the factory image in content and metadata; kernel and installer unchanged',
  'current_checks':['13 UI suites in jsdom: RU/EN, two layouts, drafts, PLOAM, MACKEY, firmware controls, native frames, login, preview',
   'CGI and boot hook with the device command set only (device-commands.txt): 50 requests incl. OUI comma rendering and no leftover temp files',
   '14 mod cases with the device command set only, incl. FwdOp pairs, 40-line log rotation and lock removal',
   'read-only diagnostics, redaction and timeouts with the device command set only',
   '27 firmware upload cases: foreign kernel/installer/tag/layout rejected, built image accepted, updater log streamed',
   'all panel shell scripts parsed by the firmware ash; awk-free code executed on the firmware BusyBox in chroot',
   'version consistency inside the built image (10 checks)'],
  'device_commands':'The SFU 240408 BusyBox lacks mv, tr, head, tail, od, cut, wc, rmdir, touch, sort, uniq, date, tee, xargs, find, seq, basename, dirname. Established from its busybox --list and its /bin/sh in chroot.',
  'preview':'jsdom; inert factory snapshots from 240408 and fictional values. No device emulation.'
 },indent=2))
 z.writestr('SHA256SUMS',checksum+'\n')
with zipfile.ZipFile(archive) as z:assert z.testzip() is None
print(json.dumps({'archive':str(archive),'bytes':archive.stat().st_size,'image':image.name,'sha256':checksum.split()[0],'rootfs_bytes':report['rootfs_bytes'],'free_rootfs_bytes':report['rootfs_limit']-report['rootfs_bytes']},indent=2))
