const fs=require('fs'),vm=require('vm'),assert=require('assert'),{JSDOM}=require('../tools/dom/node_modules/jsdom');
const delay=()=>new Promise(r=>setTimeout(r,25)),scripts=['translations.js','i18n.js','native-menu.js','mods.js','mackey.js','ploam.js','firmware.js','diagnostics.js','profiles.js','ux.js','layout.js','panel.js'];
async function app(hash='identity',pref=null,blocked=false){const errors=[],dom=new JSDOM(fs.readFileSync(__dirname+'/src/index.html','utf8'),{url:'http://onu/panel/index.html?preview=1#'+hash,runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document,c=dom.getInternalVMContext();w.confirm=()=>true;w.ODINativePreview={'/saveconf.asp':'<html><body><input disabled value=preview></body></html>'};w.addEventListener('error',e=>errors.push(e.message));if(pref!==null)w.localStorage.setItem('odi-panel-layout',pref);if(blocked){w.Storage.prototype.getItem=()=>{throw Error('denied')};w.Storage.prototype.setItem=()=>{throw Error('denied')};}for(const f of scripts)vm.runInContext(fs.readFileSync(__dirname+'/src/'+f,'utf8').replace('const preview =','let preview ='),c);await delay();return{dom,w,d,c,errors};}
(async()=>{
 const {w,d,c,errors}=await app();assert.equal(d.body.dataset.layout,'compact');assert.equal(w.localStorage.length,0);assert.equal(d.querySelectorAll('#native-nav a').length,8);
 const form=d.querySelector('[data-settings=auth]'),loid=form.elements.LOID,passwd=form.elements.LOID_PASSWD;loid.value='retain-loid';passwd.value='retain-password';loid.dispatchEvent(new w.Event('input',{bubbles:true}));
 const format=d.querySelector('#ploam-format');format.value='1';format.dispatchEvent(new w.Event('change',{bubbles:true}));const dirtyBefore=vm.runInContext('dirty',c),formatBefore=format.value;let requests=0;w.fetch=()=>{requests++;throw Error('preview must not fetch')};
 for(const mode of ['diagnostic','compact','diagnostic']){d.querySelector('[data-layout-choice='+mode+']').click();assert.equal(d.body.dataset.layout,mode);assert.equal(d.querySelector('[data-settings=auth]'),form);assert.equal(loid.value,'retain-loid');assert.equal(passwd.value,'retain-password');assert.equal(format.value,formatBefore);assert.equal(vm.runInContext('dirty',c),dirtyBefore);assert.equal(w.localStorage.getItem('odi-panel-layout'),mode);assert.equal(d.querySelector('[data-layout-choice='+mode+']').getAttribute('aria-pressed'),'true');}
 w.ODILang.set('en');await delay();assert.equal(d.querySelector('[data-layout-choice=diagnostic]').textContent,'Diagnostic');assert.equal(passwd.value,'retain-password');assert.equal(d.querySelector('#rail-hint').textContent,'Device registration and optical readings will appear here.');
 const walker=d.createTreeWalker(d.querySelector('.workspace'),4),misses=[];let n;while(n=walker.nextNode())if(/[а-яё]/i.test(n.nodeValue)&&!n.parentElement.closest('dd,pre,.mono,[data-no-translate]'))misses.push(n.nodeValue);assert.deepEqual(misses,[]);
 w.ODILang.set('ru');await delay();assert.equal(d.querySelector('[data-layout-choice=diagnostic]').textContent,'Диагностический');assert.equal(requests,0);
 // Other windows can update the presentation without discarding a draft.
 w.dispatchEvent(new w.StorageEvent('storage',{key:'odi-panel-layout',newValue:'compact'}));assert.equal(d.body.dataset.layout,'compact');assert.equal(d.querySelector('[data-settings=auth]'),form);
 // Workspace telemetry reads on a settings page, never reloads settings or writes.
 let telemetryCalls=0;w.fetch=async(url,init)=>{telemetryCalls++;assert.equal(url,'api.cgi?telemetry');assert(!init.method);return{ok:true,status:200,text:async()=>Object.entries({ok:'1',pon_state:'ONU State: 4',sampled_uptime:'99',collection_seconds:'1','optic_rx-power':'RX power: -21.5 dBm'}).map(([k,v])=>k+'='+Buffer.from(v).toString('hex')).join('\n')};};vm.runInContext("preview=false;setInterfaceLayout('diagnostic');clearTimeout(liveTimer);",c);await vm.runInContext('pollLive()',c);vm.runInContext('clearTimeout(liveTimer);',c);assert.equal(telemetryCalls,1);assert.equal(d.querySelector('#rail-stage').textContent,'O4');assert.equal(d.querySelector('#diagnostic-rail').dataset.tone,'waiting');assert.equal(d.querySelector('#rail-history-count').textContent,'1');assert(d.querySelector('#rail-optics').textContent.includes('-21.5'));assert.equal(d.querySelector('[data-settings=auth]'),form);assert.equal(loid.value,'retain-loid');
 vm.runInContext('busy=true;',c);await vm.runInContext('pollLive()',c);vm.runInContext('clearTimeout(liveTimer);',c);assert.equal(telemetryCalls,1);vm.runInContext('busy=false;liveAt=Date.now()-30000;live.pon_state="ONU State: 5";paintShellTelemetry();',c);assert.equal(d.querySelector('#diagnostic-rail').dataset.tone,'unknown');assert(d.querySelector('#rail-stamp').textContent.includes('Устарело'));assert(!d.querySelector('#rail-fresh').textContent.includes('АКТУАЛЬНО'));
 w.fetch=async()=>({ok:false,status:500,text:async()=> 'error='+Buffer.from('unavailable').toString('hex')});await vm.runInContext('pollLive()',c);vm.runInContext('clearTimeout(liveTimer);',c);assert.equal(d.querySelector('#diagnostic-rail').dataset.tone,'unknown');assert.equal(d.querySelector('[data-settings=auth]'),form);assert.equal(passwd.value,'retain-password');assert.deepEqual(errors,[]);
 let posts=0;w.fetch=async(url,init)=>{assert.equal(url,'api.cgi');assert.equal(init.method,'POST');posts++;return{ok:true,status:200,text:async()=> 'ok=31'};};vm.runInContext('liveReading=true;busy=true;state.csrf="test";',c);const write=vm.runInContext("api('save',{LOID:'test'})",c);await delay();assert.equal(posts,0);vm.runInContext('liveReading=false;',c);await write;assert.equal(posts,1);w.close();
 const a=await app('profiles','diagnostic');assert.equal(a.d.body.dataset.layout,'diagnostic');const file=a.d.querySelector('input[type=file]'),frame=a.d.querySelector('iframe');assert(file&&frame);Object.defineProperty(file,'files',{value:[{name:'chosen.json'}]});frame.contentWindow.nativeDirty=true;a.w.marker={settings:{LOID:'reference'}};vm.runInContext('state.importedProfile=window.marker;',a.c);a.d.querySelector('[data-layout-choice=compact]').click();assert.equal(a.d.querySelector('input[type=file]'),file);assert.equal(file.files[0].name,'chosen.json');assert.equal(a.d.querySelector('iframe'),frame);assert.equal(frame.contentWindow.nativeDirty,true);assert(vm.runInContext('state.importedProfile===window.marker',a.c));a.w.close();
 for(const pref of ['garbage','compact','diagnostic']){const b=await app('wan',pref);assert.equal(b.d.body.dataset.layout,pref==='diagnostic'?'diagnostic':'compact');assert(b.d.querySelector('#section-nav [data-tab=vlan]'));assert(b.d.querySelector('#section-nav [data-tab=link]'));assert(b.d.querySelector('#section-nav [data-native=lan]'));b.w.close();}
 const blocked=await app('firmware',null,true);blocked.d.querySelector('[data-layout-choice=diagnostic]').click();assert.equal(blocked.d.body.dataset.layout,'diagnostic');assert.deepEqual(blocked.errors,[]);blocked.w.close();
 fs.writeFileSync(__dirname+'/modes18-test-report.json',JSON.stringify({result:'passed',environment:'jsdom; no pixel layout or hardware test',checks:['eight stable primary sections with network subtabs','mode toggle preserves form nodes, dirty flag, password and PLOAM format','selected file and native iframe state retained','imported profile retained in memory','mode preference reload, unknown value and denied storage','cross-window layout change preserves drafts','RU/EN controls and workspace text','preview switch sends no requests','diagnostic mode reads telemetry on identity without writes or config reload','busy operation postpones telemetry','writes wait for current read to release the lock','stale and failed reads cannot show green online status','PON history and optical readings update independently of forms']},null,2));console.log('Both interface modes and draft preservation passed');
})().catch(e=>{console.error(e);process.exit(1)});
