// Optional pixel/layout checks. Serve src on localhost:8765 and provide a Playwright browser.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs'),assert=require('assert');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN}),page=await browser.newPage();const errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/index.html?preview=1#overview');await page.locator('#main h1').waitFor();
 for(const width of [320,390,768,1100,1440,1920]){await page.setViewportSize({width,height:1000});for(const mode of ['compact','diagnostic']){await page.locator('[data-layout-choice='+mode+']').click();for(const tab of ['overview','identity','wan','vlan','link','diagnostics','mods','profiles','firmware','native-password']){await page.evaluate(tab=>{location.hash=tab},tab);await page.waitForTimeout(60);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width+' '+mode+' '+tab);assert.equal(await page.locator('body').getAttribute('data-layout'),mode);assert(await page.locator('[data-layout-choice='+mode+']').isVisible());}}}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{location.hash='identity'});await page.locator('[name=LOID]').fill('keep-draft');await page.locator('[data-layout-choice=compact]').click();await page.screenshot({path:'odi-panel/preview-compact.png',fullPage:true});await page.locator('[data-layout-choice=diagnostic]').click();assert.equal(await page.locator('[name=LOID]').inputValue(),'keep-draft');await page.screenshot({path:'odi-panel/preview-diagnostic.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'odi-panel/preview-mobile.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();
 fs.writeFileSync('odi-panel/ui-test-report.json',JSON.stringify({result:'passed',environment:'Playwright preview; no hardware writes',widths:[320,390,768,1100,1440,1920],modes:2,sections:10,checks:['no page overflow','mode buttons visible','draft retained','no JS errors']},null,2));console.log('Browser geometry checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
